[book]
authors = ["bruvzz"]
language = "en"
multilingual = false
src = "src"
title = "Wave | Documentation"

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
default-theme = "frappe"